### ISSUE TITLE
Extension not showing any Problems

### ISSUE THREAD

**Issue by llMaxll** [Umoxfo/vscode-w3cvalidation#22]
I just can't get the extension working and I don't know why.
I installed it, installed jdk-14.0.1 (the currently latest), set JAVA_HOME to that jdk, added %JAVA_HOME%\bin to PATH, restarted multiple times and it still doesn't show any problems.

I don't even get any errors (like some people, when the jdk isn't found (i can't even force that error with a wrong JAVA_HOME)). So I have no clue what my problem is.

I even tried different jdk-versions (with changing JAVA_HOME), using jre instead, using open jdk, deactivating all other extensions and restarting for every new test.
I tried with and without putting the jdk-path in the extension settings, but it makes no difference.

If you need any more informations, ask.

**Comment by Umoxfo** [comment]
Please check your HTML file with [https://validator.w3.org/nu/](https://validator.w3.org/nu/).

**Comment by llMaxll** [comment]
<img width="960" alt="vscode" src="https://user-images.githubusercontent.com/22495382/81517218-76e00300-933a-11ea-8e25-7ebe9edd92f4.PNG">
<img width="891" alt="errors" src="https://user-images.githubusercontent.com/22495382/81517219-77789980-933a-11ea-8e74-6c593d32c3a2.PNG">

**Comment by Umoxfo** [comment]
Please make sure you're using the latest VS Code and extensions.

Also, keep in mind that it takes some time after the VC code is launched for the results to be displayed.

**Comment by llMaxll** [comment]
I checked again and everything is up to date.

I mostly waited some minutes while testing around and sometimes pretty long.

**Comment by groverohit** [comment]
I have the same issue. I get no errors or warnings after html is saved through the extension is installed and enabled.

**Comment by Umoxfo** [comment]
It was fixed in version 2.6.4, I hope...

**Comment by llMaxll** [comment]
I updated and still no difference for me.

Can I help you with any more information or something?

**Comment by Umoxfo** [comment]
Please try to uninstall the extension and re-install it.

**Comment by tliss** [comment]
Also not seeing any validation errors showing up.
Visual Studio Code 1.45.1 and JDK 14.0.1
Running `java -version` in command prompt works fine so I am assuming my JDK is installed correctly.

**Comment by exprosic** [comment]
Same problem here.
I would suggest to add indicators for the extension when it is doing something.
Now it's like, I followed the instruction "open your HTML document(s)", ok done, and nothing happens.
"After launching the VC code, it will take some time for the results to be displayed if the HTML is invalid", ok I'm waiting, but it just shows no sign of ending and even no sign of have started.

**Comment by cocoonkid** [comment]
I can confirm the same problem. Nothing happens at all. Thanks for fixing this 🚀

**Comment by Umoxfo** [comment]
There is no dependency on the extension except for the JDK for external dependencies.

**Comment by cocoonkid** [comment]
Okay. Really weird. I suggest adding some kind of notification that it is actually doing something and a manual trigger. 

Thanks for your great work!

**Comment by JoshuaMichaelHanson** [comment]
Try downgrading the extension version until it works.  Almost lost my mind works on MAC, but could not get to work on my windows 10, VSCode (1.62.3) machine and was demoing it for students.  Downgraded to 2.6.5 and started working again.  Installed java like 3 times and currently on JDK/JRE 13 from adopt.  Have to install the JRE and JDK separately.  Hope this helps and thanks to the developer for this, hope the new version is working soon!

**Comment by Umoxfo** [comment]
I plan to redesign the backend, but I am busy now as a college student.
It takes several months or more to release a new version; depending on my circumstance and motivation.

It is recommended that you use the official HTML checker ([https://validator.w3.org/nu/)](https://validator.w3.org/nu/) as a temporary or permanent alternative.

I apologize for any inconvenience this may cause.

**Comment by Korb** [comment]
I have the same problem. The add-on was installed from the repository in the Visual Studio Code application itself. I set the environment variables according to the recommendations in README.md. After pressing F5, the page with the corrupted html code is displayed in a separate window, and the “Problems” block still displays “No problems have been detected in the workspace”.

Visual Studio Code 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildld: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8:12.2.281.27-electron.O
OS: Microsoft Windows NT x64 10.0.19045 / 10.0.19045.4474
Java 8 Update 411 (64-bit) 8.0.4110.9
